### ISSUE TITLE
Problem with importing/exporting function from FF to WF

### ISSUE THREAD

**Issue by Kiude** [JustOff/speed-start#2]
Hello JustOff! Hello everyone!

I am a recent Waterfox user as the 57 upcoming system is pushing me to this Firefox alternative. I tried to export all my SpeedStart settings but I am having troubles as I receive the following error message after choosing the zip folder : 

[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAnnotationService.setItemAnnotation]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://sstart/content/bookmark.js :: setAnnotation :: line 81"  data: no]

I am using the Save/Restore function on the Backup menu.

Does anybody know what could cause this issue?

**Comment by JustOff** [comment]
Speed Start import works well in Waterfox, I verified this using the latest versions once again. Probably your bookmarks have some specific entries which cause the error. If it's not confidential, please send me your backup to [email](https://github.com/JustOff) and I'll try to help you.

**Comment by Kiude** [comment]
Ok! Thank you so much for offering your help!

**Comment by JustOff** [comment]
I received your backup and it seems your original Speed Start workplace in Firefox was broken.

To repair it try to do the following (in Firefox):

1. Open Speed Start home (`chrome://sstart/content/sstart.html`)
2. Right click on empty space and select `Properties`
3. Verify page background and header colors settings and press `Ok`

Then make Speed Start backup once again and try to import it into Waterfox.

**Comment by Kiude** [comment]
It worked! I should have thought about finding my way around, it could have saved you the bother.

Thank you very much! Let's go speed starting!

**Comment by JustOff** [comment]
You are welcome.
