### ISSUE TITLE
keyboard shortcut for visual bookmarks functionality

### ISSUE THREAD

**Issue by dv8472** [JustOff/speed-start#8]
Hello,

may I ask for a feature of keyboard shortcuts for the visual bookmarks?

Thank you in advance.

**Comment by JustOff** [comment]
Please be more specific.

**Comment by dv8472** [comment]
That one could specify a specific key shortcut for any visual bookmark.
For an instance, I'll create a speed dials of X visual bookmarks, and I'll be able to assign them specific key shortcuts [a-zA-Z0-9] (special characters or whatever key) with or without ctrl, alt, shift, etc, something like this: ![image](https://user-images.githubusercontent.com/22549066/88466290-14bf8480-cecb-11ea-9c85-d55143eceaf9.png)
After pressing the configured key shortcut, page will load.

**Comment by JustOff** [comment]
Sorry, but I am unlikely to implement this.

Alternatively, you can use the more general way of assigning a shortcut to any bookmark ([via](https://superuser.com/a/1078492)):
1. Install the [keyconfig](https://addons.palemoon.org/addon/keyconfig/) add-on
2. Edit your bookmark and add a unique keyword in the keyword field
3. Open Keyconfig (`Ctrl`+`Shift`+`F12`)
4. Click `Add a new key`
5. Paste following code into the text area below the name: `getShortcutOrURIAndPostData('KEYWORD').then(function(result){loadURI(result.url);});` replacing `KEYWORD` with the keyword you added to your bookmark, then click `OK`
6. Select that small text field under the list and press a key combination that you'd like to bind to your bookmark
7. Click `Apply` and you're done. You can add another shortcut or close Keyconfig window

**Comment by dv8472** [comment]
Thank you for pointing me to that workaround, works fine too.
Even better, one can put it to the user.js and distribute to another workstations.

**Comment by JustOff** [comment]
You are welcome, glad you found it helpful.
