### ISSUE TITLE
Support for Seamonkey 2.53.5.1?

### ISSUE THREAD

**Issue by suzukiyuichi44** [JustOff/speed-start#9]
I was trying to install this extension on Seamonkey 2.53.1 but it says the extension is incompatible...
or has the support for Seamonkey been dropped?

(pardon my bad English, not my 1st language, thx

*I mean, version 2.53.5.1, not 2.53.1, sorry I got it mixed up...

**Comment by JustOff** [comment]
Nothing has changed, it works just fine for me in SeaMonkey 2.53.4.

**Comment by suzukiyuichi44** [comment]
> 
> 
> Nothing has changed, it works just fine for me in SeaMonkey 2.53.4.

Sorry... I was meaning 2.53.5.1 version... what a long one...

**Comment by JustOff** [comment]
Just checked, no problems with 2.53.5.1 either.

**Comment by suzukiyuichi44** [comment]
well...
I just installed 2.15b version from github, it works now, thanks!

**Comment by JustOff** [comment]
Both 2.1.4 and 2.1.5b1 should do; you are welcome.
